# This configuration file allows our pre-commit hooks to be used with pre-commit: http://pre-commit.com/

- id: hadolint
  name: hadolint
  description: Linter for the Dockerfile
  entry: hooks/hadolint.sh
  language: script